AY2425S1-CS2103T-F11-4/tp

src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml
=> Feature: List All Client Profiles

src/main/java/seedu/address/logic/commands/AppointmentCommand.java, src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java
Fixed a bug where an invalid user input bug where a command with missing prefixes was considered valid.
=> AppointmentCommand bug fix

src/main/java/seedu/address/commons/core/index/Index.java, src/main/java/seedu/address/logic/commands/AddPropertyCommand.java, src/test/java/seedu/address/commons/core/index/IndexTest.java, src/test/java/seedu/address/logic/commands/AddPropertyCommandTest.java, src/test/java/seedu/address/logic/parser/AddPropertyCommandParserTest.java, src/test/java/seedu/address/model/person/PropertyTest.java
Create tests to check the constructor and equals method for the Property class.
Create tests to check equals, toString, and exceptional uses of AddPropertyCommand and AddPropertyCommandParser. 
Create new methods in Index to return Index as a String. Create tests for new methods in Index.
=> Create tests for Property, AddPropertyCommand and Index

src/test/java/seedu/address/logic/LogicManagerTest.java
=> Resolve issues with LogicManagerTest

src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/model/person/PersonTest.java
Changed a test case that was previously false to True when casing is different and the method to check is also changed.
=> Change name to be case-insensitive

src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/PersonListCard.fxml
Change the look of tags such that they are now rendered individually inside the PersonCard. 
Change the colour of the tags to green and the text to white.
=> Ui: Change the look of tags

src/main/java/seedu/address/model/appointment/Appointment.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/ui/PersonCardUiTest.java
Add the role beside the name.
Change the width of underline such that it dynamically follows the length of the Person's name.
=> Change the UI of PersonCard

src/main/java/seedu/address/model/listing/Region.java, src/main/java/seedu/address/model/listing/UniqueListingList.java, src/main/java/seedu/address/ui/ListingCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/ListingListCard.fxml, src/main/resources/view/ListingListPanel.fxml, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/ui/ListingCardUiTest.java
**Summary:** This PR enhances the user interface and experience of the ListingCard component, specifically by adding color-coded region indicators and aligning the region label to the top-right of the listing card. Additionally, a minor bug fix is included to prevent the unintended throwing of DuplicateListingException.
**Key Changes:**
**ListingCard UI Adjustments:**
Updated ListingListCard.fxml layout to position the region label in the top-right corner of the listing card.
Improved the design by aligning the underline element with the name label to avoid overlap.
Adjusted ListingCard Java class to dynamically apply background colors based on the listing’s region.
Made the style updates append to existing CSS classes to ensure existing styles aren’t overwritten.
**Region Enum Color …
=> Improve showListings UI + Bug Fixes

src/test/java/seedu/address/ui/ListingCardUiTest.java
Comment out ListingCardUiTest.java due to bugs in github check coverage
=> Comment out ListingCardUiTest.java

src/main/java/seedu/address/model/listing/Region.java, src/main/java/seedu/address/model/listing/UniqueListingList.java, src/main/java/seedu/address/ui/ListingCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/ListingListCard.fxml, src/main/resources/view/ListingListPanel.fxml, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/ui/ListingCardUiTest.java
**Summary:** This PR enhances the user interface and experience of the ListingCard component, specifically by adding color-coded region indicators and aligning the region label to the top-right of the listing card. Additionally, a minor bug fix is included to prevent the unintended throwing of DuplicateListingException.
**Key Changes:**
**ListingCard UI Adjustments:**
Updated ListingListCard.fxml layout to position the region label in the top-right corner of the listing card.
Improved the design by aligning the underline element with the name label to avoid overlap.
Adjusted ListingCard Java class to dynamically apply background colors based on the listing’s region.
Made the style updates append to existing CSS classes to ensure existing styles aren’t overwritten.
**Region Enum Color …
=> Improve UI for ShowListings + Bug Fixes

src/main/java/seedu/address/logic/commands/MoreInfoCommand.java, src/main/resources/view/MoreInfoWindow.css, src/test/java/seedu/address/logic/commands/MoreInfoCommandTest.java, src/test/java/seedu/address/logic/parser/MoreInfoCommandParserTest.java, src/test/java/seedu/address/ui/CommandBoxUiTest.java, src/test/java/seedu/address/ui/HelpWindowUiTest.java, src/test/java/seedu/address/ui/MoreInfoControllerUiTest.java
Pushing my limits in improving code coverage.
=> Add CommandBoxUiTest, HelpWindowUiTest, MoreInfoCommandParserTest and MoreInfoControllerUiTest

src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/logic/commands/ShowListingsCommandTest.java, src/test/java/seedu/address/testutil/TypicalIndexes.java, src/test/java/seedu/address/testutil/TypicalListings.java
Add ShowListingsCommandTest
Improve robustness of ListCommandTest
=> Add ShowListingsCommandTest and improve tests

src/main/java/seedu/address/logic/commands/AddBuyersToListingCommand.java, src/main/java/seedu/address/logic/commands/AddListingCommand.java, src/test/java/seedu/address/logic/commands/AddBuyersToListingCommandTest.java, src/test/java/seedu/address/logic/commands/AddListingCommandTest.java, src/test/java/seedu/address/logic/commands/ClearListingCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteListingCommandTest.java, src/test/java/seedu/address/logic/commands/FindListingCommandTest.java
=> Add more tests

src/main/java/seedu/address/ui/ListingCard.java, src/main/resources/view/ListingListCard.fxml
=> Display buyers list in ListingCard

src/test/java/seedu/address/logic/parser/DeletingListingCommandParserTest.java, src/test/java/seedu/address/logic/parser/FindListingsCommandParserTest.java, src/test/java/seedu/address/logic/parser/ListingParserTest.java, src/test/java/seedu/address/ui/MoreInfoControllerUiTest.java
=> Add tests for parser classes

src/main/java/seedu/address/logic/parser/EditListingCommandParser.java, src/test/java/seedu/address/logic/parser/AddBuyersToListingCommandParserTest.java, src/test/java/seedu/address/logic/parser/AppointmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditListingCommandParserTest.java, src/test/java/seedu/address/logic/parser/ListingParserTest.java, src/test/java/seedu/address/logic/parser/RemoveBuyersFromListingCommandParserTest.java
=> Add more parser test and fix editListingCommandParser bug

src/main/java/seedu/address/ui/ListingCard.java, src/test/java/seedu/address/ui/ListingCardUiTest.java
=> Fix ListingCardUiTest and boost its coverage to 100%

src/test/java/seedu/address/commons/core/ConfigTest.java, src/test/java/seedu/address/commons/core/GuiSettingsTest.java, src/test/java/seedu/address/commons/core/VersionTest.java, src/test/java/seedu/address/ui/ListingCardUiTest.java
Increased tests for ConfigTest and
GuiSettings and VersionTest
Fixed checkstyle for ListingCardUiTest
=> Increase Code Coverage

src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/ui/ChatWindow.java, src/test/java/seedu/address/ui/ChatWindowUiTest.java
=> Improve Chat Bot logic and add tests

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddBuyerProfile.java, src/main/java/seedu/address/logic/commands/AddBuyersToListingCommand.java, src/main/java/seedu/address/logic/commands/AddSellerProfile.java, src/main/java/seedu/address/logic/commands/AppointmentCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/ClearListingCommand.java, src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java, src/main/java/seedu/address/logic/commands/DeleteClientProfileCommand.java, src/main/java/seedu/address/logic/commands/DeleteListingCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/EditListingCommand.java, src/main/java/seedu/address/logic/commands/FindListingCommand.java, src/main/java/seedu/address/logic/commands/MoreInfoCommand.java, src/main/java/seedu/address/logic/commands/RemoveBuyersFromListingCommand.java, src/main/java/seedu/address/logic/parser/DeleteListingCommandParser.java, src/main/java/seedu/address/logic/parser/MoreInfoCommandParser.java, src/test/java/seedu/address/logic/parser/DeletingListingCommandParserTest.java, src/test/java/seedu/address/logic/parser/ListingParserTest.java, src/test/java/seedu/address/logic/parser/MoreInfoCommandParserTest.java, src/test/java/seedu/address/ui/CommandBoxUiTest.java, src/test/java/seedu/address/ui/MoreInfoControllerUiTest.java
Update MoreInfoCommandParser and DeleteListingCommandParser such that they do not require name prefixes.
Update usage messages to align with updated command formats.
Edit UserGuide
=> Edit parsers and usage messages

src/main/java/seedu/address/logic/parser/AddressBookParser.java
Fix #244 
Fix #245  
Fix #249  
Despite failing code coverage (because no new tests were made, just bug fixing), overall coverage went up. Should be OK to merge
=> Bug Fix: Fix several listing commands not working

src/main/java/seedu/address/ui/PersonCard.java, src/test/java/seedu/address/ui/PersonCardUiTest.java
Worst case space complexity
9999 name
9999 phone
100 tags (testing 9999 tags causes too much lag but it works)
=> Fix PersonCard to accomodate worst case space complexity

src/main/resources/view/Extensions.css
=> Ui: Fix hoverable empty list cells

src/main/java/seedu/address/ui/ListingCard.java, src/test/java/seedu/address/ui/ListingCardUiTest.java
=> ListingCard: Fix Ui to accomodate malicious input + update tests

src/main/java/seedu/address/ui/ChatWindow.java, src/test/java/seedu/address/ui/ChatWindowUiTest.java
Add respective tests.
Correct UserGuide.md.
=> Add commands to ChatWindow.java.

src/main/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommand.java, src/main/java/seedu/address/logic/commands/clientcommands/appointmentcommands/DeleteAppointmentCommand.java, src/main/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/AddAppointmentCommandParser.java, src/main/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/DeleteAppointmentCommandParser.java, src/test/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommandTest.java, src/test/java/seedu/address/logic/commands/clientcommands/appointmentcommands/DeleteAppointmentCommandTest.java, src/test/java/seedu/address/logic/parser/EzstatesParserTest.java, src/test/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/AddAppointmentCommandParserTest.java, src/test/java/seedu/address/logic/parser/clientcommandparsers/appointmentcommandparsers/DeleteAppointmentCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalIndexes.java
Reverted appointment back to use Index class to identify clients.
=> Fix Appointment Command

src/main/java/seedu/address/logic/commands/clientcommands/DeleteClientProfileCommand.java, src/main/java/seedu/address/logic/commands/clientcommands/EditClientCommand.java, src/main/java/seedu/address/logic/commands/clientcommands/appointmentcommands/AddAppointmentCommand.java, src/main/java/seedu/address/logic/commands/clientcommands/appointmentcommands/DeleteAppointmentCommand.java, src/main/java/seedu/address/logic/commands/listingcommands/DeleteListingCommand.java, src/main/java/seedu/address/logic/commands/listingcommands/EditListingCommand.java, src/main/java/seedu/address/logic/commands/listingcommands/RemoveBuyersFromListingCommand.java, src/main/java/seedu/address/ui/ChatWindow.java, src/test/java/seedu/address/ui/ChatWindowUiTest.java
=> Fix Message Usages

src/main/java/seedu/address/ui/ChatWindow.java
=> Code Quality
